name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run tests
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true

      - name: Test
        run: go test ./...

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release with goreleaser-cross
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
        run: |
          docker run --rm \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            -e GH_PAT="$GH_PAT" \
            -e AUR_KEY="$AUR_KEY" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD":/work \
            -w /work \
            --entrypoint /bin/sh \
            ghcr.io/goreleaser/goreleaser-cross:latest \
            -lc 'apt-get update >/dev/null && apt-get install -y patchelf >/dev/null && git config --global --add safe.directory /work && go mod download && goreleaser check && goreleaser release --clean'
